- name: Deploy to VPS
  uses: appleboy/ssh-action@v0.1.4
  with:
    host: ${{ secrets.VPS_HOST }}     # Your VPS IP or domain name
    username: ${{ secrets.VPS_USER }} # Your SSH username (e.g., root)
    key: ${{ secrets.VPS_KEY }}       # Your SSH private key (from GitHub Secrets)
    port: 22                          # Default SSH port is 22
    script: |
      cd rharish
      git pull origin main
      npm install
      pm2 restart all
